# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='attendance_check_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
