# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0015_courseoverview_attendance_check_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='instructors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='staff',
            field=models.TextField(null=True),
        ),
    ]
