# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0016_auto_20200511_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='total_efforts',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='total_weeks',
            field=models.TextField(null=True),
        ),
    ]
