# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0007_delete_historical_api_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccessrequest',
            name='reason',
            field=models.TextField(help_text=' \uc774 \uc0ac\uc6a9\uc790\uac00 API\uc5d0 \uc561\uc138\uc2a4\ud558\ub824\uace0 \ud558\ub294 \uc774\uc720\uc785\ub2c8\ub2e4.'),
        ),
        migrations.AlterField(
            model_name='apiaccessrequest',
            name='status',
            field=models.CharField(choices=[(b'pending', '\ub300\uae30\uc911'), (b'denied', '\uac70\uc808\ub428'), (b'approved', '\uc2b9\uc778\ub428')], db_index=True, default=b'pending', help_text=' \uc774 API \uc561\uc138\uc2a4 \uc694\uccad\uc758 \uc0c1\ud0dc ', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiaccessrequest',
            name='website',
            field=models.URLField(help_text=' \uc774 API \uc0ac\uc6a9\uc790\uc640 \uc5f0\uacb0\ub41c \uc6f9 \uc0ac\uc774\ud2b8\uc758 URL\uc785\ub2c8\ub2e4.'),
        ),
    ]
