# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollEmailDomainMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('disallow', models.BooleanField(default=False)),
            ],
        ),
    ]
