# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-27 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matchup_account',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
