# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_userprofile_matchup_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='day_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='month_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
