# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-04-12 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20200407_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='matchup_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
